name: Various experiments

on:
  push:
  pull_request:

jobs:

  gcc-8:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-20.04", "ubuntu-22.04"]
    steps:
    - uses: actions/checkout@v4
    - name: Download GCC 8
      run: |
        sudo apt-get update
        mkdir install-gcc
        cd install-gcc
        sudo apt-get update
        # INSTALL GCC
        wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-8/gcc-8_8.4.0-3ubuntu2_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-8/gcc-8-base_8.4.0-3ubuntu2_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-8/libgcc-8-dev_8.4.0-3ubuntu2_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-8/cpp-8_8.4.0-3ubuntu2_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-8/libmpx2_8.4.0-3ubuntu2_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/main/i/isl/libisl22_0.22.1-1_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-8/lib32mpx2_8.4.0-3ubuntu2_amd64.deb
        sudo apt-get install ./libisl22_0.22.1-1_amd64.deb ./libmpx2_8.4.0-3ubuntu2_amd64.deb ./cpp-8_8.4.0-3ubuntu2_amd64.deb ./libgcc-8-dev_8.4.0-3ubuntu2_amd64.deb ./gcc-8-base_8.4.0-3ubuntu2_amd64.deb ./gcc-8_8.4.0-3ubuntu2_amd64.deb ./lib32mpx2_8.4.0-3ubuntu2_amd64.deb
        which gcc-8
        # INSTALL G++
        wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-8/libstdc++-8-dev_8.4.0-3ubuntu2_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-8/g++-8_8.4.0-3ubuntu2_amd64.deb
        sudo apt-get install ./libstdc++-8-dev_8.4.0-3ubuntu2_amd64.deb ./g++-8_8.4.0-3ubuntu2_amd64.deb
        which g++-8
        # INSTALL GCC MULTILIB
        wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-8/gcc-8-multilib_8.4.0-3ubuntu2_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-8/lib32gcc-8-dev_8.4.0-3ubuntu2_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-8/libx32gcc-8-dev_8.4.0-3ubuntu2_amd64.deb
        sudo apt-get install ./gcc-8-multilib_8.4.0-3ubuntu2_amd64.deb ./lib32gcc-8-dev_8.4.0-3ubuntu2_amd64.deb ./libx32gcc-8-dev_8.4.0-3ubuntu2_amd64.deb
        sudo ln -s /usr/include/asm-generic /usr/include/asm
        # INSTALL G++ MULTILIB
        wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-8/g++-8-multilib_8.4.0-3ubuntu2_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-8/lib32stdc++-8-dev_8.4.0-3ubuntu2_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-8/libx32stdc++-8-dev_8.4.0-3ubuntu2_amd64.deb
        sudo apt-get install ./g++-8-multilib_8.4.0-3ubuntu2_amd64.deb ./lib32stdc++-8-dev_8.4.0-3ubuntu2_amd64.deb ./libx32stdc++-8-dev_8.4.0-3ubuntu2_amd64.deb
        sudo ln -fs `which gcc-8` /usr/local/bin/gcc
        sudo ln -fs `which g++-8` /usr/local/bin/g++
    - name: Test gcc version
      run: |
        gcc --version
        g++ --version
    - name: Compile simple program
      run: |
        echo 'int main() { return 0; }' > a.c
        gcc -o a.out a.c
        file a.out
        ./a.out
    - name: Compile simple C++ program
      run: |
        echo 'int main() { return 0; }' > a.cpp
        g++ -o a.out a.cpp
        file a.out
        ./a.out
    - name: Compile simple 32-bit program
      run: |
        echo 'int main() { return 0; }' > a.c
        gcc -m32 -o a.out a.c
        file a.out
        ./a.out
    - name: Compile simple 32-bit program with g++
      run: |
        echo 'int main() { return 0; }' > a.c
        g++ -m32 -o a.out a.c
        file a.out
        ./a.out
    - name: Compile zlib
      run: |
        curl -O https://zlib.net/fossils/zlib-1.2.8.tar.gz
        tar xzf zlib-1.2.8.tar.gz
        cd zlib-1.2.8
        gcc --version
        ./configure
        make clean; make test
        file minigzip
    - name: Compile zlib, 32-bits
      run: |
        cd zlib-1.2.8
        flags="-m32 -O3 -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN"
        make clean; make test CFLAGS="$flags" SFLAGS="-fPIC $flags"
        file minigzip

  gcc-8-ppa:
    if: false
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-20.04", "ubuntu-22.04"]
    steps:
    - uses: actions/checkout@v4
    - name: Download GCC 8
      run: |
        sudo add-apt-repository --yes --update ppa:ubuntu-toolchain-r/test
        sudo apt-get update
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -yq --no-install-recommends gcc-8-multilib g++-8-multilib
        which gcc-8
        which g++-8
        sudo ln -fs `which gcc-8` /usr/local/bin/gcc
        sudo ln -fs `which g++-8` /usr/local/bin/g++
        sudo ln -s /usr/include/asm-generic /usr/include/asm
    - name: Test gcc version
      run: |
        gcc --version
        g++ --version
    - name: Compile simple program
      run: |
        echo 'int main() { return 0; }' > a.c
        gcc -o a.out a.c
        file a.out
        ./a.out
    - name: Compile simple C++ program
      run: |
        echo 'int main() { return 0; }' > a.cpp
        g++ -o a.out a.cpp
        file a.out
        ./a.out
    - name: Compile simple 32-bit program
      run: |
        echo 'int main() { return 0; }' > a.c
        gcc -m32 -o a.out a.c
        file a.out
        ./a.out
    - name: Compile zlib
      run: |
        curl -O https://zlib.net/fossils/zlib-1.2.8.tar.gz
        tar xzf zlib-1.2.8.tar.gz
        cd zlib-1.2.8
        gcc --version
        ./configure
        make clean; make test
        file minigzip
    - name: Compile zlib, 32-bits
      run: |
        cd zlib-1.2.8
        flags="-m32 -O3 -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN"
        make clean; make test CFLAGS="$flags" SFLAGS="-fPIC $flags"
        file minigzip

  os-python:
    if: false
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-20.04", "ubuntu-latest", "macos-latest"]
        python-version: ["3.10", "pypy2.7", "pypy3.9"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Test python version
      run: |
        python -c 'import sys;print(sys.version)'
        python --version
    - name: Test dependencies ${{ matrix.python-version }} ${{ startsWith(matrix.python-version, 'pypy') }} ${{ matrix.os }} ${{ startsWith(matrix.os, 'macos') }} ${{ ! startsWith(matrix.os, 'macos') }} ${{ ! startsWith(matrix.python-version, 'pypy') || ! startsWith(matrix.os, 'macos') }} ${{ (! startsWith(matrix.python-version, 'pypy')) || (! startsWith(matrix.os, 'macos')) }}
      # pypy on macosx is really too slow
      if: ${{ ! startsWith(matrix.python-version, 'pypy') || ! startsWith(matrix.os, 'macos') }}
      run: |
        python -m pip install pytest pyparsing coverage codecov

  python23:
    if: false
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 2.3
      run: |
        CWD=$(pwd)
        cd ..
        curl -O https://www.python.org/ftp/python/2.3.7/Python-2.3.7.tgz
        tar xzf Python-2.3.7.tgz
        cd Python-2.3.7
        # We need to disable FORTIFY_SOURCE to compile python 2.3
        # cf. https://bugs.launchpad.net/ubuntu/+source/gcc-defaults/+bug/286334
        ./configure BASECFLAGS=-U_FORTIFY_SOURCE
        make
        export PATH=$(pwd):$PATH
        cd $CWD
    - name: Test python version
      run: |
        python -c 'import sys;print(sys.version)'
        python --version

  gcc:
    if: false
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-20.04", "ubuntu-22.04"]
        gcc-version: ["4.4", "4.6", "4.8", "5", "6", "7", "8", "9", "10", "11", "12"]
        platform: ["x64", "x86"]
        exclude:
          - {os: ubuntu-20.04, gcc-version: 12}
          - {os: ubuntu-20.04, gcc-version: 13}
          - {os: ubuntu-22.04, gcc-version: 8}
          - {os: ubuntu-22.04, gcc-version: 4.4}
          - {os: ubuntu-22.04, gcc-version: 4.6}
    env:
      CC: gcc
    steps:
    - uses: actions/checkout@v3
    - name: Set up GCC ${{ matrix.gcc-version }}
      uses: LRGH/setup-gcc@v2
      with:
        version: ${{ matrix.gcc-version }}
        platform: ${{ matrix.platform }}
    - name: Test gcc version
      run: |
        $CC --version
    - name: Compile simple program
      run: |
        case "${{ matrix.platform }}" in x86) CPU=-m32 ;; *) CPU= ;; esac
        echo 'int main() { return 0; }' > a.c
        $CC $CPU -o a.out a.c
        file a.out
        ./a.out
    - name: Compile zlib
      run: |
        curl -O https://zlib.net/fossils/zlib-1.2.8.tar.gz
        tar xzf zlib-1.2.8.tar.gz
        cd zlib-1.2.8
        ./configure
        make clean; make test CC="$CC $CPU"
        file minigzip
        # curl --upload-file minigzip 'https://paste.c-net.org/'
        # gcc -O3 -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -S -o minigzip.s test/minigzip.c
        # gcc -O3 -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -c -o minigzip.o test/minigzip.c
        # curl --upload-file minigzip.s 'https://paste.c-net.org/'
        # curl --upload-file minigzip.o 'https://paste.c-net.org/'

  gcc-m32:
    if: false
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
        gcc-version: [4.4, 4.6, 4.8, 5, 6, 7, 8, 9, 10, 11, 12, 13]
        platform: [x86]
        exclude:
          - {os: ubuntu-22.04, gcc-version: 4.4}
          - {os: ubuntu-22.04, gcc-version: 4.6}
          - {os: ubuntu-22.04, gcc-version: 4.8, platform: x86}
          - {os: ubuntu-20.04, gcc-version: 4.8}
          - {os: ubuntu-20.04, gcc-version: 5}
          - {os: ubuntu-22.04, gcc-version: 5, platform: x86}
          - {os: ubuntu-20.04, gcc-version: 6}
          - {os: ubuntu-22.04, gcc-version: 6, platform: x86}
          - {os: ubuntu-20.04, gcc-version: 7}
          - {os: ubuntu-22.04, gcc-version: 8}
          - {os: ubuntu-20.04, gcc-version: 9}
          - {os: ubuntu-20.04, gcc-version: 10}
          - {os: ubuntu-20.04, gcc-version: 11}
          - {os: ubuntu-20.04, gcc-version: 12}
          - {os: ubuntu-20.04, gcc-version: 13}
    steps:
    - uses: actions/checkout@v4
    - name: Set up GCC ${{ matrix.gcc-version }}
      uses: LRGH/setup-gcc@v3
      with:
        version: ${{ matrix.gcc-version }}
        platform: ${{ matrix.platform }}
    - name: Test gcc version
      run: |
        gcc --version
    - name: Compile simple 32-bit program
      run: |
        echo 'int main() { return 0; }' > a.c
        gcc -m32 -o a.out a.c
        file a.out
        ./a.out
    - name: Using #include <errno.h>
      run: |
        echo '#include <errno.h>' > a.c
        echo 'int main() { return 0; }' >> a.c
        gcc -m32 -o a.out a.c
        file a.out
        ./a.out
    - name: Compile zlib, 32-bits
      run: |
        curl -O https://zlib.net/fossils/zlib-1.2.8.tar.gz
        tar xzf zlib-1.2.8.tar.gz
        cd zlib-1.2.8
        ./configure
        flags="-m32 -O3 -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN"
        make clean; make test CFLAGS="$flags" SFLAGS="-fPIC $flags"
        file minigzip

  gcc-8-zzz:
    if: false
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-20.04", "ubuntu-22.04"]
    steps:
    - uses: actions/checkout@v4
    - name: Download GCC 8
      run: |
        sudo apt-get update
        mkdir install-gcc
        cd install-gcc
        wget https://old-releases.ubuntu.com/ubuntu/pool/universe/g/gcc-8/g++-8_8.4.0-7ubuntu3_amd64.deb
        wget https://old-releases.ubuntu.com/ubuntu/pool/universe/g/gcc-8/libstdc++-8-dev_8.4.0-7ubuntu3_amd64.deb
        wget https://old-releases.ubuntu.com/ubuntu/pool/universe/g/gcc-8/gcc-8-base_8.4.0-7ubuntu3_amd64.deb
        wget https://old-releases.ubuntu.com/ubuntu/pool/universe/g/gcc-8/gcc-8_8.4.0-7ubuntu3_amd64.deb
        wget https://old-releases.ubuntu.com/ubuntu/pool/universe/g/gcc-8/libgcc-8-dev_8.4.0-7ubuntu3_amd64.deb
        wget https://old-releases.ubuntu.com/ubuntu/pool/universe/g/gcc-8/cpp-8_8.4.0-7ubuntu3_amd64.deb
        wget http://archive.ubuntu.com/ubuntu/pool/main/g/glibc/libc6_2.35-0ubuntu3_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/main/g/gcc-8/libubsan1_8.4.0-1ubuntu1~18.04_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/main/g/gcc-8/libmpx2_8.4.0-1ubuntu1~18.04_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/main/i/isl/libisl22_0.22.1-1_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/main/i/isl/libisl23_0.26-3_amd64.deb
        lib32=""; if test ${{ matrix.platform }} = x86; then
          true
        fi
        sudo apt-get install ./g++-8_8.4.0-7ubuntu3_amd64.deb ./libstdc++-8-dev_8.4.0-7ubuntu3_amd64.deb ./gcc-8-base_8.4.0-7ubuntu3_amd64.deb ./gcc-8_8.4.0-7ubuntu3_amd64.deb ./libgcc-8-dev_8.4.0-7ubuntu3_amd64.deb ./cpp-8_8.4.0-7ubuntu3_amd64.deb ./libc6_2.35-0ubuntu3_amd64.deb ./libubsan1_8.4.0-1ubuntu1~18.04_amd64.deb ./libmpx2_8.4.0-1ubuntu1~18.04_amd64.deb ./libisl22_0.22.1-1_amd64.deb ./libisl23_0.26-3_amd64.deb $lib32
        sudo ln -fs `which gcc-8` /usr/local/bin/gcc
        sudo ln -fs `which g++-8` /usr/local/bin/g++
    - name: Test gcc version
      run: |
        gcc --version
    - name: Compile simple program
      run: |
        echo 'int main() { return 0; }' > a.c
        gcc -o a.out a.c
        file a.out
        ./a.out
    - name: Compile simple C++ program
      run: |
        echo 'int main() { return 0; }' > a.cpp
        g++ -o a.out a.cpp
        file a.out
        ./a.out
    - name: Compile simple 32-bit program
      run: |
        echo 'int main() { return 0; }' > a.c
        gcc -m32 -o a.out a.c
        file a.out
        ./a.out
    - name: Compile zlib
      run: |
        curl -O https://zlib.net/fossils/zlib-1.2.8.tar.gz
        tar xzf zlib-1.2.8.tar.gz
        cd zlib-1.2.8
        gcc --version
        ./configure
        make clean; make test
        file minigzip
    - name: Compile zlib, 32-bits
      run: |
        cd zlib-1.2.8
        flags="-m32 -O3 -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN"
        make clean; make test CFLAGS="$flags" SFLAGS="-fPIC $flags"
        file minigzip

  alpine:
    if: false
    runs-on: ubuntu-latest
    steps:
    - uses: jirutka/setup-alpine@v1
      with:
        # branch: v3.15
        arch: x86
        packages: >
          file
          sudo
          curl
          tar
          bzip2
          m4
          build-base
          make
    - run: cat /etc/alpine-release
      shell: alpine.sh {0}
    - name: Generic
      run: |
        uname -a
        uname -m
        file /usr/bin/dash
    - name: Alpine
      run: |
        uname -a
        uname -m
        file /bin/busybox
      shell: alpine.sh {0}
    - name: simple C compilation
      run: |
        gcc --version
        echo 'int main() { return 0; }' > a.c
        gcc -o a.out a.c
        file a.out
        ./a.out
      shell: alpine.sh {0}
    - name: GMP 4.3.2
      run: |
        curl -O https://ftp.gwdg.de/pub/misc/gcc/infrastructure/gmp-4.3.2.tar.bz2
        bzip2 -cd gmp-4.3.2.tar.bz2 | tar xf -
        cd gmp-4.3.2
        ./configure
        make
        sudo make install
      shell: alpine.sh {0}
    - name: MPFR 2.4.2
      run: |
        curl -O https://ftp.gwdg.de/pub/misc/gcc/infrastructure/mpfr-2.4.2.tar.bz2
        bzip2 -cd mpfr-2.4.2.tar.bz2 | tar xf -
        cd mpfr-2.4.2
        ./configure
        make
        sudo make install
      shell: alpine.sh {0}
    - name: MPC 0.8.1
      run: |
        curl -O https://ftp.gwdg.de/pub/misc/gcc/infrastructure/mpc-0.8.1.tar.gz
        tar xzf mpc-0.8.1.tar.gz
        cd mpc-0.8.1
        ./configure
        make
        sudo make install
      shell: alpine.sh {0}
    - name: GCC 4.9.2
      run: |
        curl -O https://ftp.gnu.org/gnu/gcc/gcc-4.9.2/gcc-4.9.2.tar.gz
        tar xzf gcc-4.9.2.tar.gz
        cd gcc-4.9.2
        ./configure
        make
      shell: alpine.sh {0}
    - name: GCC 3.2.3
      run: |
        curl -O https://ftp.gnu.org/gnu/gcc/gcc-3.2.3.tar.gz
        tar xzf gcc-3.2.3.tar.gz
        cd gcc-3.2.3
        ./configure
        make
      shell: alpine.sh {0}
